#!/bin/bash

#SBATCH --partition=gpu_mig
#SBATCH --gpus=1
#SBATCH --job-name=main_fastdetectGPT
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=04:00:00
#SBATCH --output=output/slurm_output_%A.out

module purge
module load 2023
module load Anaconda3/2023.07-2

# activate your conda environment
bash setup.sh
source activate fastdetectGPT

# Your job starts in the directory where you call sbatch
cd $HOME/DL4NLP-Group15/fast-detectGPT
# Run your code
bash main.sh